name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/ci.yml'
      - 'rootfs/**'
      - 'Dockerfile'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2.3.4

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Docker meta
        if: success()
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: fengsiio/october
          tag-semver: |
            {{ version }}
            {{major}}.{{minor}}

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        if: success()
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Registry
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          build-args: OCTOBER_VERSION=${{ steps.get_version.outputs.version }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
